apiVersion: v1
kind: Namespace
metadata:
    name: gitlab
    labels:
      name: gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-data
    labels:
      release: gitlab-data
    namespace: gitlab
spec:
    capacity:
      storage: 500Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /gitlab/data
      server: xxx.xxx.nas.aliyuncs.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-kubeconfig
    labels:
      release: gitlab-kubeconfig
    namespace: gitlab
spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /gitlab/kubeconfig
      server: xxx.xxx.nas.aliyuncs.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-log
    labels:
      release: gitlab-log
    namespace: gitlab
spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /gitlab/log
      server: xxx.xxx.nas.aliyuncs.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-claim
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      release: gitlab-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-kubeconfig-claim
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      release: gitlab-kubeconfig
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-log-claim
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      release: gitlab-log